# إيقاف تصغير HTML/JS الذي يكسر الكود
[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = false

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
    X-Frame-Options = "SAMEORIGIN"
